ruby "1.9.3"
# If you have OpenSSL installed, we recommend updating
# the following line to use "https"
source 'http://rubygems.org'


gem "thin"
gem "rack-contrib"

gem "middleman", "~>3.2.0"
# Live-reloading plugin
gem "middleman-livereload", "~> 3.1.0"
gem "middleman-smusher"
gem "middleman-favicon-maker"

# For faster file watcher updates on Windows:
gem "wdm", "~> 0.1.0", :platforms => [:mswin, :mingw]

# Adds syntax highlighting via Rouge
gem "middleman-syntax"
gem "redcarpet"

gem "slim"
gem "bootstrap-sass"
gem "sassy-buttons"

group :development do
	gem "heroku"
	gem 'foreman'
	gem 'therubyracer'
	gem 'oj'
end

group :production do
	gem 'therubyracer-heroku'
	gem 'oj'
end